[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
]
build-backend = "setuptools.build_meta"

[project]
name = "clingexplaid"
authors = [
    { name = "Hannes Weichelt", email = "hweichelt@uni-potsdam.de" },
    { name = "Susana Hahn", email = "susuhahnml@yahoo.com.mx" }
]
maintainers = [{ name = "Hannes Weichelt", email = "hweichelt@uni-potsdam.de" }]
description = "Tools to aid the development of explanation systems using clingo"
requires-python = ">=3.10"
license = {file = "LICENSE"}
dynamic = [ "version" ]
readme = "README.md"
dependencies = [
	"clingo>=5.7.1",
    "musclingo @ file:///${PROJECT_ROOT}/../musclingo",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/potassco/clingo-explaid"
Source = "https://github.com/potassco/clingo-explaid"
"Issues" = "https://github.com/potassco/clingo-explaid/issues"

[project.optional-dependencies]
lint = [ "ruff" ]
typecheck = ["pytest", "ty"]
test = ["pytest", "pytest-cov", "coverage[toml]"]
doc = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings>=1.0.4",
    "mkdocstrings-python>=2.0",
    "clindocs>=1.5.1",
    "mkdocs-literate-nav",
    "pygments_clingo",
]
dev = [ "clingexplaid[test,typecheck,lint,lint_pylint]" ]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"
local_scheme = "no-local-version"

[tool.ruff]
line-length = 120
target-version = "py310"
exclude = [
    "/usr/**",
    "**/site-packages/**",
    "**/node_modules/**",
    "**/typeshed-fallback/**",
]

[tool.ruff.lint]
extend-select = ["I", "E", "F", "B", "C4", "D", "ARG", "SIM", "ANN", "Q"]
ignore = [
    "E741",
    "D200",
    "D203",
    "D212",
    "D413",
    "B023", # broken lint
    "D107", # don't require a docstring for constructors
]

[tool.ruff.lint.per-file-ignores]
"noxfile.py" = ["ANN"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"


[tool.coverage.run]
source = ["clingexplaid", "tests"]
omit = [
    "*/clingexplaid/propagators/*",
    "*/clingexplaid/transformers/__init__.py",
    "*/clingexplaid/muc/__init__.py",
    "*/clingexplaid/unsat_constraints/__init__.py",
    "*/tests/*",
    "*/constants.py",
    "*/clingexplaid/utils/match.py",
]

[tool.coverage.report]
exclude_lines = ["assert", "nocoverage"]
